name: module3_task4

on:
  push:
    branches: 
      - main
    tags:
      - '1.0.1'

  pull_request:
    branches: 
      - main

  schedule:
    - cron: "0 0 * * *"

jobs:
  tag:
    runs-on: ubuntu-18.04
    steps:
      - name: cloning
        uses: actions/checkout@v2

      - name: set_up
        run: cd module3_task4 && sudo ./setup.sh

      - name: build
        run: cd module3_task4 && make build

      - name: run unit-tests
        run: cd module3_task4 && make unit-tests

      - name: run integration-tests
        run: cd module3_task4 && make integration-tests

      - name: run validate
        run: cd module3_task4 && make validate

      - name: lint
        run: cd module3_task4 && npm install -g markdownlint-cli && make lint

      - name: package
        run: cd module3_task4 && make package

      - name: release_tag
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/1.0.1')
        with:
          files: |
            module3_task4/awesome-website.zip
            module3_task4/DEPLOY.md
          body_path: module3_task4/DEPLOY.md
